{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-params",
    "version": "5.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.10.0.jar",
          "url": "junit-jupiter-params-5.10.0.jar",
          "size": 586027,
          "sha512": "444de835650129217093dbdb473a5df559a80cad25aa636fa7516b83dd6461628a8823592dc110786bb1bf09d7685123bfee4e5e9d0778b6301e96c13fe17463",
          "sha256": "f259a7322cce375430c2236a2dcb24d4a49d22045b723ad85af88e11704391c2",
          "sha1": "9041c7365495a897a64782ea5a6fdb99dab1814e",
          "md5": "f005062186389c756ce58cb380190cc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.10.0.jar",
          "url": "junit-jupiter-params-5.10.0.jar",
          "size": 586027,
          "sha512": "444de835650129217093dbdb473a5df559a80cad25aa636fa7516b83dd6461628a8823592dc110786bb1bf09d7685123bfee4e5e9d0778b6301e96c13fe17463",
          "sha256": "f259a7322cce375430c2236a2dcb24d4a49d22045b723ad85af88e11704391c2",
          "sha1": "9041c7365495a897a64782ea5a6fdb99dab1814e",
          "md5": "f005062186389c756ce58cb380190cc4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.10.0-javadoc.jar",
          "url": "junit-jupiter-params-5.10.0-javadoc.jar",
          "size": 276578,
          "sha512": "a6c4601d5d9371d1c4323bd6d281fbdd0e12572f75a8eae8fd126385792e8580b43bf330b94b3bbc5a1ea96fba030b412cb7f21395d22d367b1bcc436890e70c",
          "sha256": "1bbfc19de84f36dc536ed4d0658ce2a53359834e12ee4e11cb57217b70346b10",
          "sha1": "a613b0f439275e303138f56762789c307ee50dd4",
          "md5": "d85714cd1152f3a66938c2fc0cd9d39a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.10.0-sources.jar",
          "url": "junit-jupiter-params-5.10.0-sources.jar",
          "size": 77757,
          "sha512": "627fa495f97edd33ec356fd185b30f0e9db914d63f28e7f2ad69be2ac36543252c267eddb6433dc8d6c109f60d7dd27c3f662a0f4c56bbeb8b8a061a4356165b",
          "sha256": "7d20740d1dded4cb1de5805c3da3293b6a5e2991ad3b64539aa575c9638719dc",
          "sha1": "06c4fb5ab59bbc63438f3c618d769c4eddd65654",
          "md5": "654f23c40cf633bb9ca0f35a8b401e5c"
        },
        {
          "name": "junit-jupiter-params-5.10.0-sources.jar",
          "url": "junit-jupiter-params-5.10.0-sources.jar",
          "size": 77757,
          "sha512": "627fa495f97edd33ec356fd185b30f0e9db914d63f28e7f2ad69be2ac36543252c267eddb6433dc8d6c109f60d7dd27c3f662a0f4c56bbeb8b8a061a4356165b",
          "sha256": "7d20740d1dded4cb1de5805c3da3293b6a5e2991ad3b64539aa575c9638719dc",
          "sha1": "06c4fb5ab59bbc63438f3c618d769c4eddd65654",
          "md5": "654f23c40cf633bb9ca0f35a8b401e5c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.10.0.jar",
          "url": "junit-jupiter-params-5.10.0.jar",
          "size": 586027,
          "sha512": "444de835650129217093dbdb473a5df559a80cad25aa636fa7516b83dd6461628a8823592dc110786bb1bf09d7685123bfee4e5e9d0778b6301e96c13fe17463",
          "sha256": "f259a7322cce375430c2236a2dcb24d4a49d22045b723ad85af88e11704391c2",
          "sha1": "9041c7365495a897a64782ea5a6fdb99dab1814e",
          "md5": "f005062186389c756ce58cb380190cc4"
        }
      ]
    }
  ]
}
